### ISSUE TITLE
Functional Correctness

### ISSUE THREAD

**Issue by emarzion** [PalindromeLeung/PathORAM#40]
### Laws:

- [x] **read-write law:** v <- read k; write k v == return ()
- [x] **write-read law:**  write(key,value) ; read(key)  == write(key,value) ; return(value)
- [x]  **read-read law:** v <- read(key) ; read(key) == v <- read(key) ; return(v)
- [x]  **read-commute law:** v1 <- read(key1) ; v2 <- read(key2) ; f(v1,v2) == v2 <- read(key2) ; v1 <- read(key1) ; f(v1,v2)
- [x]  **read-write-commute law (requires key1 =/= key2):** v <- read(key1); write(key2,value); f(v) == write(key2,value) ; v <- read(key1) ; f(v)
- [x]  **write-commute law (requires key1 =/= key2):** write(key1,value1) ; write(key2,value2) == write(key2,value2) ; write(key1,value1)
- [x] **write-absorb law:** write k v; write k v' == write k v'

### Admits:

- [x] `read_wf` says that the `read` operation preserves well-formedness
- [x] `read_pres_kv` says that the `read` operation preserves a kv pair
- [x] `read_pres_undef` says that `read` operation preserves undefinedness of a key
- [x] `write_wf` says that the `write` operation preserves well-formedness
- [x] `write_undef` says that `write k v` preserves undefinedness of `k'` for `k <> k'`
- [x] `write_val_neq` says that `kv_rel k' v'` is preserved by `write k v` for `k <> k'`
- [x] `read_undef_0` says that if a key `k` is undefined, then the lookup value of `k` is `0`.
- [x]  `write_near_stable` says that `write k v` doesn't affect keys other than `k`.

**Comment by PalindromeLeung** [comment]
Yay we did it!

**Comment by PalindromeLeung** [comment]
Yayyyyyy we did it!
